[pad]
[pad.motors]
drive_front = 2
drive_rear = 2

suspension_front = 3
suspension_rear = 4

[pad.encoders]
suspension_front_left = 1
suspension_front_right = 2
suspension_rear_left = 3
suspension_rear_right = 4

[system]
[system.motors]
test_one = 1
