[pad]
[pad.motors]
drive_front = 0
drive_rear = 0

suspension_front = 1
suspension_rear = 2

[pad.encoders]
drive_front_left = 0
drive_front_right = 1
drive_rear_left = 2
drive_rear_right = 5
arm_base = 3
arm_upper = 4

[pad.servos]
analog_camera1_pan = 0
analog_camera1_tilt = 1


[system]
[system.motors]
test_one = [1, 2]
test_two = [3, 4]
[system.limit_switches]
test_one = 1
[system.status_leds]
red = 0
green = 1
blue = 2
