[pad]
[pad.motors]
drive_front = 0
drive_rear = 0

suspension_front = 1
suspension_rear = 2

bio_arm_yaw = 3
bio_arm_auger = 3

arm_lower_cycloidal = 3
arm_yaw = 3

[pad.encoders]
drive_front_left = 2
drive_front_right = 1
drive_rear_left = 0
drive_rear_right = 5
arm_base = 3
arm_upper = 4

[pad.servos]
analog_camera1_pan = 0
analog_camera1_tilt = 1

arm_pitch = 3
arm_roll = 4

arm_pwm_upper_cycloidal = 2


[system]
pca9685_path = "/dev/i2c-1"
[system.servos]
analog_camera1_pan = 0
analog_camera1_tilt = 1
[system.motors]
bio_arm_vertical = [394, 467]
bio_arm_centrifuge = [397, 255]
[system.limit_switches]
# test_one = 397
[system.status_leds]
# red = 0
# green = 1
# blue = 2
